In [156]:
import pandas as pd
import numpy as np

In [157]:
df=pd.read_csv("C:\\Users\\jojic\\OneDrive\\Desktop\\mljourney\\cleaning-works\\drug-use\\drug200.csv")

In [158]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [159]:
df[df.duplicated].shape

(0, 6)

In [160]:
x=df.iloc[:,:-1] 
y=df.iloc[:,-1]
x.head()

   Age Sex      BP Cholesterol  Na_to_K
0   23   F    HIGH        HIGH   25.355
1   47   M     LOW        HIGH   13.093
2   47   M     LOW        HIGH   10.114
3   28   F  NORMAL        HIGH    7.798
4   61   F     LOW        HIGH   18.043

In [161]:
df["Drug"].unique()

array(['DrugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [162]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("encoder",OneHotEncoder(),["Sex","Cholesterol","BP"])],remainder="passthrough")
x=pd.DataFrame(ct.fit_transform(x))
x.head()

     0    1    2    3    4    5    6     7       8
0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  23.0  25.355
1  0.0  1.0  1.0  0.0  0.0  1.0  0.0  47.0  13.093
2  0.0  1.0  1.0  0.0  0.0  1.0  0.0  47.0  10.114
3  1.0  0.0  1.0  0.0  0.0  0.0  1.0  28.0   7.798
4  1.0  0.0  1.0  0.0  0.0  1.0  0.0  61.0  18.043

In [163]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([0, 3, 3, 4, 0, 4, 0, 3, 0, 0, 3, 0, 0, 0, 4, 0, 4, 1, 3, 0, 0, 0,
       0, 0, 0, 0, 0, 4, 0, 0, 4, 2, 4, 0, 4, 4, 1, 4, 4, 4, 0, 2, 0, 4,
       4, 4, 1, 3, 0, 0, 0, 4, 0, 0, 2, 3, 2, 0, 4, 0, 0, 1, 0, 4, 2, 0,
       1, 4, 0, 0, 2, 0, 4, 0, 0, 0, 1, 0, 1, 4, 2, 4, 3, 1, 3, 2, 4, 0,
       0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 1, 1, 3, 4, 0, 4, 4, 0, 2, 0,
       1, 4, 4, 4, 4, 0, 4, 4, 1, 0, 0, 0, 0, 0, 2, 0, 0, 4, 0, 4, 0, 0,
       4, 0, 0, 4, 2, 1, 2, 4, 1, 0, 2, 0, 1, 4, 4, 1, 4, 3, 1, 2, 4, 4,
       0, 3, 1, 0, 3, 4, 4, 2, 4, 0, 0, 0, 0, 4, 0, 1, 4, 4, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 4, 4, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 3, 0, 3, 3, 4,
       4, 4])

In [164]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [165]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [166]:
from imblearn.over_sampling import SMOTE
sm=SMOTE(random_state=42)
x_train_smote,y_train_smote = sm.fit_resample(x_train,y_train)

In [167]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn = KNeighborsClassifier()
knn.fit(x_train_smote,y_train_smote)
y_pred = knn.predict(x_test)
print("accuracy_score",accuracy_score(y_test,y_pred)*100)

accuracy_score 90.0

In [168]:
params = {
    "n_neighbors":[3,5,7,9],
    "weights":["uniform","distance"],
    "algorithm":["auto","ball_tree","kd_tree","brute"]
}

In [169]:
from sklearn.model_selection import GridSearchCV
gs = GridSearchCV(knn,params,cv=10)
gs.fit(x_train_smote,y_train_smote)
gs.best_params_

{'algorithm': 'auto', 'n_neighbors': 3, 'weights': 'distance'}

In [170]:
knn = KNeighborsClassifier(algorithm="auto",n_neighbors=3,weights="distance")
knn.fit(x_train_smote,y_train_smote)
y_pred = knn.predict(x_test)
print("accuracy_score",accuracy_score(y_test,y_pred)*100)

accuracy_score 90.0

In [171]:
import joblib
joblib.dump(knn,"dt_model.pkl")
joblib.dump(scaler,"scaler.pkl")

['scaler.pkl']